### ISSUE TITLE
small config issues

### ISSUE THREAD

**Issue by Martimiz** [praxisnetau/silverstripe-module-starter#1] opened 2017-11-03 13:25 UTC
Hi,
First of all many many thanks for setting up this supernice and much needed module!!! 

I've run into a couple of small config issues that I'll address in one topic, if you don't mind :) 

## yarn
yarn.lock should probably be added to .gitignore I think

## package.json: 
running yarn install fails with:

    The engine "node" is incompatible with this module. Expected version "^4.2.0".

That's because I'm using v8.6.0 and in package.json you have

  "engines": {
    "node": "^4.2.0"
  },

Could that just be removed, you think?

## webpack
running yarn build fails with:

    [copy-webpack-plugin] WARNING - unable to locate 'mymodule/admin/client/src/images/icons'...

That directory isn't actually created, but referenced in webpack.config.js #127:

      if (src === PATHS.ADMIN.SRC) {
        common.push(
          new CopyWebpackPlugin([
            { from: path.resolve(src, 'images/icons'), to: 'images/icons' }
          ])
        );
      }

Should this be removed or should there be an actual icons folder. And is it supposed to contain icons? 

Cheers, Martine

**Comment by colintucker** [comment] 2017-11-03 23:10
Hi @Martimiz !

Thanks for submitting this issue, I'll go through each of your points:

>yarn.lock should probably be added to .gitignore I think

Actually, the lock file should _explicitly_ be [added to version control](https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all). This ensures that everyone has the same dependencies installed from the get go. You can always delete the lock file yourself and customise the `package.json` to install the versions of your choice.

>running yarn install fails with "The engine "node" is incompatible with this module. Expected version "^4.2.0".

Hmm, it works fine for me with v8.4.0. Something else must be going wrong I think, because the version check "^4.2.0" should definitely work for your version of node. That said, I could probably bump the version requirement up to "^6.x" in line with SilverStripe's current requirements.

>...should there be an actual icons folder. And is it supposed to contain icons?

Ah, when I committed to version control, my icons folder was empty, hence the structure was not added to the repo.  I should make a note about that or perhaps add a "dummy" file in there. In the mean time, if you create `images/icons/` under your `admin/client/src/` folder, the error will disappear.

**Comment by micschk** [comment] 2018-04-30 04:15
Hi @colintucker, this module is really helpful for getting into the whole new front-end SilverStripe ecosystem, thanks!
Just to confirm; using node v8.11.1 indeed throws an 'incompatible version' error upon 'yarn install'. 
Also for a version constraint of "^6.x" (which would only allow any v6 point release but not v8 I think?)
The SilverStripe 'webpack bundles' repo uses ">= 6.x" (any 6.x version or higher, which I can confirm works with 8.x) https://github.com/silverstripe/webpack-config

**Closed as completed** 2018-08-22 00:20 UTC
